name = "Expanding North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6070c0f9f51848bd0462fcfbfe49f00e4bd13a03c63e140650053cc78be475b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
