name = "Expanding North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68e71fae0bcd8406de670b15d4a3b550de9f0ff26f7e19298741b788c788714f"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
